### ISSUE TITLE
Docs unclear on Phoenix usage

### ISSUE THREAD

**Issue by amencarini** [ggpasqualino/plug_checkup#12]
In the docs it says

> Forward your health path to PlugCheckup in your Plug Router

```
forward "/health",
  to: PlugCheckup,
  init_opts: %PlugCheckup.Options{checks: checks}
```

This can be confusing when using Phoenix as the Phoenix.Router implements a different `forward/4` function that takes a different set of arguments than `forward/2` in Plug.Router.

Happy to add an example if you think it's worth it.

**Comment by ggpasqualino** [comment]
Hey @amencarini, that would be great
